### PR TITLE
Added cmake support

### PR DESCRIPTION
**Pull request by C4e10VeK**

### CODE REVIEW

**Comment by MihailRis** [comment]
Ubuntu Release 20.04.3 LTS 
cmake output:
```
-- The C compiler identification is GNU 9.4.0
-- The CXX compiler identification is GNU 9.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found OpenGL: /usr/lib/x86_64-linux-gnu/libOpenGL.so   
-- Found GLEW: /usr/include (found version "2.1.0") 
-- Found OpenAL: /usr/lib/x86_64-linux-gnu/libopenal.so  
-- Found ZLIB: /usr/lib/x86_64-linux-gnu/libz.so (found version "1.2.11") 
-- Found PNG: /usr/lib/x86_64-linux-gnu/libpng.so (found version "1.6.37") 
-- Configuring done
CMake Error at CMakeLists.txt:7 (add_executable):
  Target "VoxelEngine" links to target "OpenAL::OpenAL" but the target was
  not found.  Perhaps a find_package() call is missing for an IMPORTED
  target, or an ALIAS target is missing?
```

**(libopenal-dev is installed)**

**Comment by C4e10VeK** [comment]
Updated links. Should now compile on Ubuntu 20.04 LTS

**Comment by MihailRis** [comment]
glm is header-only library 
```/usr/bin/ld: cannot find -lglm```

excluded glm from target_link_libraries:
```
/usr/bin/ld: CMakeFiles/VoxelEngine.dir/src/voxels/ChunksController.cpp.o: undefined reference to symbol 'pthread_create@@GLIBC_2.2.5'
/usr/bin/ld: /lib/x86_64-linux-gnu/libpthread.so.0: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
```

**Comment by C4e10VeK** [comment]
updated CMakeLists.txt. Everything was tested on the arch дштгч. And everything works. There is no possibility to check on other linux distro
